### ISSUE TITLE
Add remaining zint generators (pdf417)

### ISSUE THREAD

**Issue by Caellian** [Enter-tainer/zint-wasi#1]
pdf417 is commonly used by banking applications so it would be very useful for generating invoices. But in general, given that there's already an enum of supported generators, why not add all of them.

I created a local copy of the plugin and added it, it ended up being a 1 line change for the pdf417 one.

**Comment by Enter-tainer** [comment]
I think it's supported but a shorthand is missing. Can you open a pr and add it?
<img width="714" alt="image" src="https://github.com/Enter-tainer/zint-wasi/assets/25521218/a263345e-4a19-4fe6-8abf-7a55eff622b3">
