### ISSUE TITLE
Unexpected argument `options`

### ISSUE THREAD

**Issue by sonovice** [Enter-tainer/zint-wasi#3]
Thank you for your library. However, I am not able to pass any `options`:
![image](https://github.com/Enter-tainer/zint-wasi/assets/8217108/84bf73c2-5328-4c4b-b152-085408a51e43)

**Comment by Enter-tainer** [comment]
Which version are you using? Also please kindly paste code here so I can reproduce and fix the problem

**Comment by Enter-tainer** [comment]
Please use `#import "@preview/tiaoma:0.2.0"`. I forgot to update the code block in [readme](https://typst.app/universe/package/tiaoma). So I guess you might be using 0.1.0

**Comment by sonovice** [comment]
Thanks, updating `0.2.0` indeed did the trick!

**Comment by Enter-tainer** [comment]
ty, I will publish 0.2.1 to fix the readme then
