### ISSUE TITLE
qrcode option_3 not allow mask

### ISSUE THREAD

**Issue by lublak** [Enter-tainer/zint-wasi#4]
based on the documentation, you can use mask in option_3 in qrcode:

 QR Code has eight different masks designed to minimize unwanted patterns. The best mask to use is selected automatically by Zint but may be manually specified by using the --mask switch with values 0-7, or in the API by setting option_3 = (N + 1) << 8 where N is 0-7. To use with ZINT_FULL_MULTIBYTE set

option_3 = ZINT_FULL_MULTIBYTE | (N + 1) << 8

https://github.com/Enter-tainer/zint-wasi/blob/master/zint-wasm-rs/src/options/option3.rs#L55

But currently you can only use ZINT_FULL_MULTIBYTE. 
But it should be possible to use option_3 = (N + 1) << 8 and ZINT_FULL_MULTIBYTE | (N + 1) << 8

**Comment by Caellian** [comment]
Does using an `int` value for `option-3` not produce expected results?

**Comment by lublak** [comment]
@Caellian i got an: `Semantic(None, "invalid option value for option_3: 2048")` because if you look at the code, only ZINT_FULL_MULTIBYTE  is accepted not all int values.

**Comment by Caellian** [comment]
Try using the [fix/qr-mask-opt3](https://github.com/Enter-tainer/zint-wasi/tree/fix/qr-mask-opt3) branch, I allowed use of `(N + 1) << 8` values and made the enum non-exhaustive.
